name: msf_flow
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.7
  - numpy=1.18.5
  - pygrib=2.0.4
  - utm=0.5.0
  - matplotlib=3.3.0
  - idna=2.10
  - requests=2.24.0
  - python-dateutil=2.8.1
  - pip=20.1.1
  - pandas=1.0.5
  - geopandas=0.8.1