name: cmml-cpu
channels:
- pytorch
- nvidia
- conda-forge
dependencies:
- python=3.10
- numpy
- matplotlib
- notebook
- scipy
- tqdm
- scikit-learn
- scikit-image
- rasterio
- pytorch
- torchvision
- torchaudio
- cpuonly
