name: base
channels:
- conda-forge
dependencies:
- affine=2.4.0
- attrs=23.1.0
- aws-c-auth=0.7.3
- aws-c-cal=0.6.1
- aws-c-common=0.9.0
- aws-c-compression=0.2.17
- aws-c-event-stream=0.3.1
- aws-c-http=0.7.11
- aws-c-io=0.13.32
- aws-c-mqtt=0.9.3
- aws-c-s3=0.3.14
- aws-c-sdkutils=0.1.12
- aws-checksums=0.1.17
- aws-crt-cpp=0.21.0
- aws-sdk-cpp=1.10.57
- blosc=1.21.4
- boost-cpp=1.78.0
- brotli=1.0.9
- brotli-bin=1.0.9
- brotli-python=1.0.9
- bzip2=1.0.8
- c-ares=1.19.1
- ca-certificates=2023.7.22
- cairo=1.16.0
- certifi=2023.7.22
- cfitsio=4.3.0
- charset-normalizer=3.2.0
- click=8.1.6
- click-plugins=1.1.1
- cligj=0.7.2
- colorama=0.4.6
- contourpy=1.1.0
- cycler=0.11.0
- expat=2.5.0
- filelock=3.12.2
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.2
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.42.0
- freetype=2.12.1
- freexl=1.0.6
- geos=3.12.0
- geotiff=1.7.1
- gettext=0.21.1
- giflib=5.2.1
- gmp=6.2.1
- gmpy2=2.1.2
- hdf4=4.2.15
- hdf5=1.14.1
- icu=72.1
- idna=3.4
- jinja2=3.1.2
- json-c=0.17
- kealib=1.5.1
- kiwisolver=1.4.4
- krb5=1.21.2
- lcms2=2.15
- lerc=4.0.0
- libaec=1.0.6
- libarchive=3.6.2
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcblas=3.9.0
- libcurl=8.2.1
- libdeflate=1.18
- libedit=3.1.20191231
- libev=4.33
- libexpat=2.5.0
- libffi=3.4.2
- libgdal=3.7.1
- libgfortran5=12.3.0
- libglib=2.76.4
- libiconv=1.17
- libjpeg-turbo=2.1.5.1
- libkml=1.3.0
- liblapack=3.9.0
- libnetcdf=4.9.2
- libnghttp2=1.52.0
- libopenblas=0.3.23
- libpng=1.6.39
- libpq=15.4
- libprotobuf=3.21.12
- librttopo=1.1.0
- libspatialite=5.0.1
- libsqlite=3.42.0
- libssh2=1.11.0
- libtiff=4.5.1
- libuv=1.44.2
- libwebp-base=1.3.1
- libxcb=1.15
- libxml2=2.11.5
- libzip=1.9.2
- libzlib=1.2.13
- llvm-openmp=16.0.6
- lz4-c=1.9.4
- lzo=2.10
- markupsafe=2.1.3
- matplotlib=3.7.2
- matplotlib-base=3.7.2
- mpc=1.3.1
- mpfr=4.2.0
- mpmath=1.3.0
- munkres=1.1.4
- ncurses=6.4
- networkx=3.1
- nomkl=1.0
- nspr=4.35
- nss=3.89
- numpy=1.25.2
- openjpeg=2.5.0
- openssl=3.1.2
- packaging=23.1
- pcre2=10.40
- pillow=10.0.0
- pip=23.2.1
- pixman=0.40.0
- poppler=23.08.0
- poppler-data=0.4.12
- postgresql=15.4
- proj=9.2.1
- pthread-stubs=0.4
- pyparsing=3.0.9
- pysocks=1.7.1
- python=3.11.4
- python-dateutil=2.8.2
- python_abi=3.11
- pytorch=2.0.0
- rasterio=1.3.8
- readline=8.2
- requests=2.31.0
- setuptools=68.0.0
- six=1.16.0
- sleef=3.5.1
- snappy=1.1.10
- snuggs=1.4.7
- sqlite=3.42.0
- sympy=1.12
- tiledb=2.16.3
- tk=8.6.12
- torchvision=0.15.2
- tornado=6.3.2
- tqdm=4.66.1
- typing_extensions=4.7.1
- tzcode=2023c
- tzdata=2023c
- urllib3=2.0.4
- wheel=0.41.1
- xerces-c=3.2.4
- xorg-libxau=1.0.11
- xorg-libxdmcp=1.1.3
- xz=5.2.6
- zlib=1.2.13
- zstd=1.5.2

