name: base
channels:
- conda-forge
- nvidia
- pytorch
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- affine=2.4.0
- alsa-lib=1.2.8
- attr=2.5.1
- attrs=23.1.0
- blas=1.0
- blosc=1.21.4
- boost-cpp=1.78.0
- brotli=1.0.9
- brotli-bin=1.0.9
- brotli-python=1.0.9
- bzip2=1.0.8
- c-ares=1.19.1
- ca-certificates=2023.7.22
- cairo=1.16.0
- certifi=2023.7.22
- cfitsio=4.2.0
- charset-normalizer=3.2.0
- click=8.1.7
- click-plugins=1.1.1
- cligj=0.7.2
- colorama=0.4.6
- contourpy=1.1.0
- cuda-cudart=11.8.89
- cuda-cupti=11.8.87
- cuda-libraries=11.8.0
- cuda-nvrtc=11.8.89
- cuda-nvtx=11.8.86
- cuda-runtime=11.8.0
- curl=8.1.2
- cycler=0.11.0
- dbus=1.13.6
- expat=2.5.0
- ffmpeg=4.3
- fftw=3.3.10
- filelock=3.12.2
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.2
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.42.0
- freetype=2.12.1
- freexl=1.0.6
- geos=3.11.1
- geotiff=1.7.1
- gettext=0.21.1
- giflib=5.2.1
- glib=2.76.4
- glib-tools=2.76.4
- gmp=6.2.1
- gmpy2=2.1.2
- gnutls=3.6.13
- graphite2=1.3.13
- gst-plugins-base=1.22.0
- gstreamer=1.22.0
- gstreamer-orc=0.4.34
- harfbuzz=6.0.0
- hdf4=4.2.15
- hdf5=1.12.2
- icu=70.1
- idna=3.4
- jack=1.9.22
- jinja2=3.1.2
- jpeg=9e
- json-c=0.16
- kealib=1.5.0
- keyutils=1.6.1
- kiwisolver=1.4.4
- krb5=1.20.1
- lame=3.100
- lcms2=2.15
- ld_impl_linux-64=2.40
- lerc=4.0.0
- libaec=1.0.6
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcap=2.67
- libcblas=3.9.0
- libclang=15.0.7
- libclang13=15.0.7
- libcublas=11.11.3.6
- libcufft=10.9.0.58
- libcufile=1.7.1.12
- libcups=2.3.3
- libcurand=10.3.3.129
- libcurl=8.1.2
- libcusolver=11.4.1.48
- libcusparse=11.7.5.86
- libdb=6.2.32
- libdeflate=1.17
- libedit=3.1.20191231
- libev=4.33
- libevent=2.1.10
- libexpat=2.5.0
- libffi=3.4.2
- libflac=1.4.3
- libgcc-ng=13.1.0
- libgcrypt=1.10.1
- libgdal=3.6.2
- libgfortran-ng=13.1.0
- libgfortran5=13.1.0
- libglib=2.76.4
- libgpg-error=1.47
- libhwloc=2.9.1
- libiconv=1.17
- libkml=1.3.0
- liblapack=3.9.0
- libllvm15=15.0.7
- libnetcdf=4.9.1
- libnghttp2=1.52.0
- libnpp=11.8.0.86
- libnsl=2.0.0
- libnvjpeg=11.9.0.86
- libogg=1.3.4
- libopus=1.3.1
- libpng=1.6.39
- libpq=15.2
- librttopo=1.1.0
- libsndfile=1.2.2
- libspatialite=5.0.1
- libsqlite=3.42.0
- libssh2=1.11.0
- libstdcxx-ng=13.1.0
- libsystemd0=253
- libtiff=4.5.0
- libtool=2.4.7
- libudev1=253
- libuuid=2.38.1
- libvorbis=1.3.7
- libwebp-base=1.3.1
- libxcb=1.13
- libxkbcommon=1.5.0
- libxml2=2.10.3
- libzip=1.9.2
- libzlib=1.2.13
- llvm-openmp=16.0.6
- lz4-c=1.9.4
- markupsafe=2.1.3
- matplotlib=3.7.2
- matplotlib-base=3.7.2
- mkl=2022.2.1
- mpc=1.3.1
- mpfr=4.2.0
- mpg123=1.31.3
- mpmath=1.3.0
- munkres=1.1.4
- mysql-common=8.0.33
- mysql-libs=8.0.33
- ncurses=6.4
- nettle=3.6
- networkx=3.1
- nspr=4.35
- nss=3.89
- numpy=1.25.2
- openh264=2.1.1
- openjpeg=2.5.0
- openssl=3.1.2
- packaging=23.1
- pcre2=10.40
- pillow=9.4.0
- pip=23.2.1
- pixman=0.40.0
- ply=3.11
- poppler=23.03.0
- poppler-data=0.4.12
- postgresql=15.2
- proj=9.1.1
- pthread-stubs=0.4
- pulseaudio=16.1
- pulseaudio-client=16.1
- pulseaudio-daemon=16.1
- pyparsing=3.0.9
- pyqt=5.15.9
- pyqt5-sip=12.12.2
- pysocks=1.7.1
- python=3.11.4
- python-dateutil=2.8.2
- python_abi=3.11
- pytorch=2.0.1
- pytorch-cuda=11.8
- pytorch-mutex=1.0
- qt-main=5.15.8
- rasterio=1.3.6
- readline=8.2
- requests=2.31.0
- setuptools=68.1.2
- sip=6.7.11
- six=1.16.0
- snappy=1.1.10
- snuggs=1.4.7
- sqlite=3.42.0
- sympy=1.12
- tbb=2021.9.0
- tiledb=2.13.2
- tk=8.6.12
- toml=0.10.2
- tomli=2.0.1
- torchaudio=2.0.2
- torchtriton=2.0.0
- torchvision=0.15.2
- tornado=6.3.3
- tqdm=4.66.1
- typing_extensions=4.7.1
- tzcode=2023c
- tzdata=2023c
- urllib3=2.0.4
- wheel=0.41.1
- xcb-util=0.4.0
- xcb-util-image=0.4.0
- xcb-util-keysyms=0.4.0
- xcb-util-renderutil=0.3.9
- xcb-util-wm=0.4.1
- xerces-c=3.2.4
- xkeyboard-config=2.38
- xorg-kbproto=1.0.7
- xorg-libice=1.1.1
- xorg-libsm=1.2.4
- xorg-libx11=1.8.4
- xorg-libxau=1.0.11
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.10
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xz=5.2.6
- zlib=1.2.13
- zstd=1.5.2
